### ISSUE TITLE
Drupal Status Report showing errors

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#162]
#### Issue description

Having created a New ISLE site following the instructions here https://islandora-collaboration-group.github.io/ISLE-Documentation/03_installation_new_site/new_site_installation_guide_single/, I've logged into my new Drupal site as the admin, navigated the `Status Report` section https://islandora-docker.com/node#overlay=admin/reports/status, and noticed multiple errors and/or warnings.

#### Steps to reproduce the issue

1.  Create new ISLE site
2. Login to the newly created Drupal site (in my case, islandora-docker.com)
3. Navigate to https://islandora-docker.com/node#overlay=admin/reports/status (Status Report Section) and view 

#### What's the expected result?

- No errors other than a prompt to create XML sitemap (expected as cron has not run yet) and perhaps a Module and theme update status depending on the last Drupal update and time of ISLE build.

#### What's the actual result?

**- Error 1:**

(In blue)
```
Database 4 byte UTF-8 support | Not enabled

4 byte UTF-8 for mysql is not activated, but it is supported on your system. It is recommended that you enable this to allow 4-byte UTF-8 input such as emojis, Asian symbols and mathematical symbols to be stored correctly. See the documentation on adding 4 byte UTF-8 support for more information.
```

This should be enabled. I believe this was not an error prior and more than likely can be resolved during the build process of the mysql image. Recommend ISLE Maintainers review https://www.drupal.org/node/2754539 for appropriate fixes.

**- Error 2:**

(In red)
```
HTTP request status | Fails

Your system or network configuration does not allow Drupal to access web pages, resulting in reduced functionality. This could be due to your webserver configuration or PHP settings, and should be resolved in order to download information about available updates, fetch aggregator feeds, sign in via OpenID, or use other network-dependent services. If you are certain that Drupal can access web pages but you are still seeing this message, you may add $conf['drupal_http_request_fails'] = FALSE; to the bottom of your settings.php file.
```

I'm not sure what the issue here is per se and recommend an ISLE maintainer review and test.  Simply reporting.

**- Error 3:**

(in yellow)
```
MySQL - max allowed packet | 4 MB

Your MySQL 'max_allowed_packet' setting may be too low for Views data export to function correctly, Drupal's requirements recommend setting it to at least 16M. See: http://drupal.org/requirements
```

Not sure what happened here but indeed it should be 16M or higher.

#### Additional details / screenshot

- ![screen shot 2018-09-14 at 16 53 11](https://user-images.githubusercontent.com/501554/45574652-b7723b00-b83e-11e8-889c-202cc820edf7.png)

**Comment by g7morris** [comment]
Thank you for the fix however for testers it would be appreciated if a next steps response would be posted when necessary. In this case, I think for those getting onboarded with ISLE, they'd potentially need it. 

In this instance, would it be fair to assume I need to first:

* `docker-compose stop` to stop all running containers

* delete my current containers, `docker rm isle-mysql-id` etc

* `docker pull` the `image-services` image 

* `docker-compose up -d`

Resume testing for this situation and confirming that the issue has ceased. If resolved, leave the ticket closed, if not reopen.

**Comment by br2490** [comment]
Hey @g7morris I'm nearing the final few updates for this.  Thank you again for reporting all of these issues #162 #163 #164!  I realize you're right that we're missing some docs on "How to Update" which would list the commands to update the images and restart updated containers && "Testing: Steps to take a maintainer pushes a development update to resolve issues during testing phases." 
I was wondering if you wouldn't mind creating an issue for that with the DOCS tag, and you can of course assign: @marksandford and @br2490!
When I'm done here with #162 I'll pop instructions in here for how to fetch this update!

Thank you, Gavin!! 💯

**Comment by br2490** [comment]
This is resolved but may reveal an additional issue:
@g7morris To test this update there several options:

Please use this method if you can to verify if the util scripts are being updated:
- Restart the apache container `docker restart isle-apache-ld` (Assuming `CONTAINER_SHORT_ID` in the .env file is `ld` if not, replace appropriate env value.  This should pull the latest build tools on start.  In my own testing _this did not happen_.  
To check if build_tools are being updated:
  - `docker exec -it isle-apache-ld bash` (assuming `CONTAINER_SHORT_ID`)
  - `cd /utility-scripts/isle_drupal_build_tools  && git rev-parse --short HEAD`
  - Output _should_ read: `f59fb4c`
  - If not please run:  `git fetch --all && git reset origin/master --hard`

- Start fresh `docker-compose down -v` and `docker-compose up -d` then run the installer.

**Comment by g7morris** [comment]
@br2490 Confirming I followed your steps above and found the value of `f59fb4c` as requested. There was no need to follow the steps beyond that point. 

From the Status report now, it appears that **Error 3** has been fixed and as such is not being reported any more. 

However **Error 1** and **Error 2** are still occurring.

Should I restart testing from scratch at this point and confirm if errors still occur? No problem to do so.

**Comment by br2490** [comment]
Thank you for confirming the update script for install script works!
In my original steps I failed to mention: please re-run the install script
on isle-apache after the update! I've copied this from the quickstart guide:
docker exec -it isle-apache-ld bash
/utility-scripts/isle_drupal_build_tools/isle_islandora_installer.sh



Benjamin Rosner

Instructional Application Developer
Instructional Media and Technology,
Barnard Library and Academic Information Services
p: 212-854-9005

**Comment by br2490** [comment]
MySQL was updated to 5.7 and the my.cnf from ISLE 1 was actually ported
directly (why replace something that works?)
Later it was found that the conf file was actually not being parsed (hence
the errors) as it had invalid settings for MySQL 5.7.  The MySQL container
was updated and when you ran `docker-compose pull` this AM (for the other
updates) it will have grabbed the new image with settings.
To review the current settings in My5.7 checkout the github repo
https://github.com/Islandora-Collaboration-Group/isle-mysql and report back
if you notice anything missing, please! (check in the rootfs folder.)


Benjamin Rosner

Instructional Application Developer
Instructional Media and Technology,
Barnard Library and Academic Information Services
p: 212-854-9005

**Comment by g7morris** [comment]
@br2490 Indeed! Upon the complete site rebuild, confirming all green on Drupal Status Reports! Thanks very much. Closing ticket.
